### PR TITLE
Non Ansi Console support

### PR DESCRIPTION
**Pull request by Ahuge**
Hey @rahiel. I was getting garbled text when attempting to configure on windows and decided to make a pull request for windows/non-ansi support.

I don't have easy access to a linux vm but will attempt to test it on linux shortly.

### CODE REVIEW

**Comment by rahiel** [comment]
Thanks for the PR! Don't worry testing on Linux though, I think I have have a simpler solution:

Using [colorama](https://github.com/tartley/colorama) for colour support and a different prompt character only on windows. @Ahuge would you mind helping to test on windows when it's ready?

===

I also had some comments on this PR:

The `supports_ansi` function was pulled from a gist, and we need explicit permission to have it included in this GPLv3+ project.

I dislike calling `supports_ansi` every time `markup` is invoked: `supports_ansi` should be run once and the resulting boolean should be put in a variable, that we can reuse to check in `markup`

**Comment by Ahuge** [comment]
For sure, thanks @rahiel 

Are you working on colorama or should I get started on it?

**Comment by rahiel** [comment]
@Ahuge I worked on adding colorama and released a new version that should work on windows, could you update and test it?
```
pip install telegram-send --upgrade
```

**Comment by Ahuge** [comment]
Hey @rahiel colorama seems to be working correctly. Here's a snapshot

image


Thanks for setting that up!

**Comment by rahiel** [comment]
Cool! Thanks for testing! :smile: 

Let me know if you encounter other issues.

**Pull request closed without merging**
