### PR TITLE
Update for PTB v20

### PR DESCRIPTION
**Pull request by luk1337**

### CODE REVIEW

**Comment by DeadNews** [comment]
@rahiel
Please, review this PR.

**Comment by DeadNews** [comment]
@rahiel
Please review PR https://github.com/rahiel/telegram-send/pull/124.

Or at least specify a valid range of `python-telegram-bot` versions. 
https://github.com/rahiel/telegram-send/blob/34d7703754d441a6f4c4a7b5b3210759d36078e2/setup.py#L22
It should be, for example, `>=13.0,<14.0`.

refs: https://github.com/rahiel/telegram-send/issues/115 https://github.com/rahiel/telegram-send/issues/122

**Comment by omidontop** [comment]
Any updates on the approval?

**Comment by rahiel** [comment]
@luk1337 thanks for your valuable contribution!

Looks great!

**Pull request merged**
