### PR TITLE
Changed MAX_MESSAGE_LENGTH constant

### LINKED ISSUE #115: cannot import name 'MAX_MESSAGE_LENGTH' from 'telegram.constants'
`pip install --user --upgrade --force-reinstall telegram-send && telegram-send --configure`

`ImportError: cannot import name 'MAX_MESSAGE_LENGTH' from 'telegram.constants' (/home/user/.local/lib/python3.10/site-packages/telegram/constants.py)`

### PR DESCRIPTION
**Pull request by george-gca**
Fixes #115.

### CODE REVIEW

**Comment by afonsojramos** [comment]
@rahiel can you check this out?

**Comment by maierp** [comment]
@rahiel  I did those changes by hand and it works now. Would be great if this pull request could be integrated.

**Comment by george-gca** [comment]
While @rahiel doesn't approve the pr, downgrade `python-telegram-bot`

```bash
pip3 install --force-reinstall -v "python-telegram-bot==13.5"
```

or install the package like this:

```bash
pip3 install git+https://github.com/george-gca/telegram-send
```

**Comment by maierp** [comment]
Hey thank you so much 😊👍
All the beat
Patrick

Am 01.03.2023 20:19 schrieb George ***@***.***>:

While @rahiel<https://github.com/rahiel> doesn't approve the pr, downgrade python-telegram-bot

pip3 install --force-reinstall -v "python-telegram-bot==13.5"

or install the package like this:

pip3 install git+https://github.com/george-gca/telegram-send

**Comment by Takaogahara** [comment]
Any update on this branch?

**Comment by raccoon4x** [comment]
Perhaps this edit is no longer relevant, because. further errors occur. Perhaps due to the next update of the python-telegram-bot library.

**Comment by Casul51** [comment]
> While @rahiel doesn't approve the pr, downgrade `python-telegram-bot`
> 
> ```shell
> pip3 install --force-reinstall -v "python-telegram-bot==13.5"
> ```
> 
> or install the package like this:
> 
> ```shell
> pip3 install git+https://github.com/george-gca/telegram-send
> ```

After system update got all updated while breaking telegram-send for my system. Resolved (or delayed))) A TON of work thanks to You! So I have working telegram-send. Have no idea why @raccon4x didn't get it

**Comment by rahiel** [comment]
These changes are included in the recently merged #124

**Pull request closed without merging**
